---
title: "Bowtie2 results"
author: "Renee Matthews"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 400px;
}
```


```{r}
library(tidyverse)
library(readr)
```

```{r loading mapping stat files}
DOX_ChIP_samplenames <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/DOX_ChIP_samplenames.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
set1_parsed <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/mapping_stats/set1_parsed.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
set2_parsed <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/mapping_stats/set2_parsed.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
set3_parsed <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/mapping_stats/set3_parsed.tsv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)


Mapping_stats_combo <-
set1_parsed %>% 
  bind_rows(.,set2_parsed) %>%  
  bind_rows(.,set3_parsed) %>% 
  left_join(., DOX_ChIP_samplenames, by =c("sample_name"="Sample name")) %>% 
  mutate(total_reads=total_reads*2)

my_colors=c(CTCF="blue",RAD21="purple",TOP2B="red",p53="violet",Input_P53="pink")
pd <- position_dodge(width = 0.75)
```

```{r}

Mapping_stats_combo %>% 
  ggplot(aes(x=sample_name, y=alignment_rate)) +
  geom_col(aes(fill=Ab))+
  theme_bw()+
  scale_fill_manual(values=my_colors)+
  ggtitle("Alignment rate by sample")+
theme(axis.text.x=element_text(vjust= .2,angle=90))

Mapping_stats_combo %>% 
  ggplot(aes(x=Individual, y=alignment_rate)) +
  geom_boxplot()+
  geom_point(aes(color=Ab, size=3))+
  theme_bw()+
  facet_wrap(~Tx)+
  scale_color_manual(values=my_colors)+
  ggtitle("Alignment rate by individual")
   
Mapping_stats_combo %>% 
  ggplot(aes(x=Tx, y=alignment_rate)) +
  geom_boxplot()+
  geom_point(aes(color=Individual, size=3))+
  theme_bw()+
  facet_wrap(~Ab)+
  ggtitle("Alignment for each individual by treatment")


```
```{r}
Mapping_stats_combo %>% 
  ggplot(aes(x=sample_name, y=concord_1_pct)) +
  geom_col(aes(fill=Ab))+
  theme_bw()+
  scale_fill_manual(values=my_colors)+
  ggtitle("Percent concordantly mapping 1 time by sample")+
theme(axis.text.x=element_text(vjust= .2,angle=90))


Mapping_stats_combo %>% 
  ggplot(aes(x=Individual, y=concord_1_pct)) +
  geom_boxplot()+
  geom_point(aes(color=Ab, size=3))+
  theme_bw()+
  facet_wrap(~Tx)+
  scale_color_manual(values=my_colors)+
  ggtitle("Percent concordantly mapping 1 time by individual")
   
Mapping_stats_combo %>% 
  ggplot(aes(x=Tx, y=concord_1_pct)) +
  geom_boxplot()+
  geom_point(aes(color=Individual, size=3))+
  theme_bw()+
  facet_wrap(~Ab)+
  ggtitle("Percent concordantly mapping 1 time each individual\nby treatment")
```

```{r plot_reads, fig.height=7, fig.width=8}



read_count_summary <- read_csv("C:/Users/renee/Other_projects_data/DOX_CHIP/Stat_data/full_summary_read_counts.csv")

final_counts_file <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/Stat_data/final_counts_file.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
read_count_summary %>% 
  dplyr::select(Sample:Properly_Paired) %>% 
  left_join(final_counts_file) %>% 
  left_join(DOX_ChIP_samplenames, by =c("Sample"="Sample name")) %>% 
    mutate(Tx=factor(Tx, levels = c("VEH","DOX")),
           Ab=factor(Ab, levels = c("TOP2B","p53","CTCF","RAD21","Input_P53")),
           Type=factor(Type, levels=c("ChIP_DNA","Input_DNA"))) %>% 
  pivot_longer(., cols=c(Properly_Paired:noBL), names_to = "read_type", values_to = "R1_R2_counts") %>% 
  mutate(read_type=factor(read_type,levels=c("Properly_Paired","PropPairedUnique","Nuclear","Dedup","noBL"))) %>% 
  ggplot(., aes(x=read_type, y=R1_R2_counts))+
  geom_boxplot(aes(fill=Tx), position=pd)+
  geom_point(aes(color=Individual,group = Tx),
             position = pd, size = 2)+
  facet_wrap(~Ab+Type, scale="free_y")+
  scale_color_brewer(palette = "Dark2")+
  theme_bw()+
  
  theme(strip.text = element_text(face = "bold",  hjust = 0, size = 8),
        strip.background = element_rect(fill = "white", linetype = "solid",
                                        color = "black", linewidth = 1),
        panel.spacing = unit(1, 'points'),
        axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1))
  

```


```{r}


blacklist_filter_summary <- read_delim("C:/Users/renee/Other_projects_data/DOX_CHIP/Stat_data/blacklist_filter_summary.tsv", 
 delim = "\t", escape_double = FALSE, 
   trim_ws = TRUE)
```

